server:
  port: 3081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: customer
        uri: http://localhost:3001/
        predicates:
        - Path=/customers/**
      - id: order
        uri: http://localhost:3002/
        predicates:
        - Path=/orders/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true